spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


otel:
  sdk:
    disabled: false
  exporter:
    otlp:
      endpoint: https://cloud.langfuse.com/api/public/otel
      headers:
        authorization: Basic cGstbGYtOWZkYTIwZDgtYjg3ZC00YTYyLWE2MGEtMTU2Yzc4OTYyYjAwOnNrLWxmLTFhMWJiNzBkLTU2YzYtNDg1Yy04ZDcxLWNmNjA3ZGMzZWJhOQ==
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: otlp
  service:
    name: vector-search-app